### ISSUE TITLE
数字部分分类逻辑

### ISSUE THREAD

**Issue by KamioRinn** [juntaosun/LangSegment#2]
```python
textlist = ["【齐鲁艺票通】恭喜您购票成功！","订单编号：","669775550013131,","取票码：","93342253；","请凭取票码在演出开始前30分钟到指定地点换取纸质票。"]
for text in textlist:
    print(LangSegment.getTexts(text))
# [{'lang': 'zh', 'text': '【齐鲁艺票通】恭喜您购票成功！'}]
# [{'lang': 'zh', 'text': '订单编号：'}]
# [{'lang': 'en', 'text': '669775550013131, '}]
# [{'lang': 'zh', 'text': '取票码：'}]
# [{'lang': 'en', 'text': '93342253； '}]
# [{'lang': 'zh', 'text': '请凭取票码在演出开始前30分钟到指定地点换取纸质票。'}]
```

大佬。整句输入判定正常，当用户选择按标点符号切割时，纯数字会被识别为英文，能否改成参照上文的逻辑处理？

**Comment by juntaosun** [comment]
for text in textlist:
    #  循环里，这里文本已经是你切好的；
    #  送入getTexts的值实际只有一个独立的数字： text = "669775550013131,"。
    print(LangSegment.getTexts(text))

相当于是 LangSegment.getTexts("669775550013131,")。返回的结果也是"669775550013131,"
在切分textlist 的时候，把数字和上句拼接一下。

**Comment by juntaosun** [comment]
我想到的另一个最简单的办法，就是先让 LangSegment 分词，再从分词里切。
（1）第一步：LangSegment 分词。以下这个是分词的结果列表。
{'lang': 'zh', 'text': '【齐鲁艺票通】恭喜您购票成功！订单编号：6697****3131,取票码：93**2253；请凭取票码在演出开始前30分钟到指定地点换取纸质票，换票地址：山东烟台市牟平区工商大街910号牟平大剧院，剧院联系电话：0**5-7***3。'}
（2）第二步：它们的语言已经确定，你直接在这里结果面切分，同一个text里的语言都是lang一样了=zh。

**Comment by KamioRinn** [comment]
> 我想到的另一个最简单的办法，就是先让 LangSegment 分词，再从分词里切。 （1）第一步：LangSegment 分词。以下这个是分词的结果列表。 {'lang': 'zh', 'text': '【齐鲁艺票通】恭喜您购票成功！订单编号：6697*_**3131,取票码：932253；请凭取票码在演出开始前30分钟到指定地点换取纸质票，换票地址：山东烟台市牟平区工商大街910号牟平大剧院，剧院联系电话：05-7**_3。'} （2）第二步：它们的语言已经确定，你直接在这里结果面切分，同一个text里的语言都是lang一样了=zh。

好咧，谢谢。

**Comment by juntaosun** [comment]
你好，在最近更新的版本: v0.2.1 中，我们添加了语言优先级功能：

```python
# 升级版本命令：
pip3 install LangSegment>=0.2.1 -i https://pypi.org/simple
``` 

PS：只需要调整语言过滤器的顺序，就可以调整语言优先级。以下是介绍示例：  

```python
# 仅输入独立纯数字：所有国家通用，因为没有提供上下文，所以无法区分语言归属
print(LangSegment.getTexts("123456789")) # 国际纯数字，默认输出：英文=en

# 【A】调整过滤语言优先级，中文（zh）优先，数字按中文优先识别
LangSegment.setfilters(["zh","ja"])
print(LangSegment.getTexts("123456789")) # 识别输出：中文=zh

# 【B】调整过滤语言优先级，日语（ja）优先，数字按日语优先识别
LangSegment.setfilters(["ja","zh"])
print(LangSegment.getTexts("123456789")) # 识别输出：日文=ja
```

**Comment by KamioRinn** [comment]
优先级功能很强，有没有考虑增加对一些常见单位的识别支持？
比如 kg、cm、m等英文单位现在夹在一句完整中文中间也会被分离出去。
