### ISSUE TITLE
有些中文会被误识别为日文

### ISSUE THREAD

**Issue by fsqinghuayu** [juntaosun/LangSegment#5]
输入说我炒菜咸！显示语言为ja
![20240308-114250](https://github.com/juntaosun/LangSegment/assets/38353004/aab20629-ac66-44d6-abc7-97d0b4dad3a8)

**Comment by juntaosun** [comment]
升级下版本：

`
pip3 install LangSegment>=0.2.5 -i https://pypi.org/simple
`
